name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "m**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build/Install
      run: cargo b -vv && cargo install --path . -vv
    - run: |
        slow_loris 23.54.155.142 &
    - run: pkill -f slow_loris;
    - name: Run tests
      run: cargo test --verbose -- 23.54.155.142 --timeout 60
